/*
 Roundtable
 (c) 2021 Nikola Sibalic
*/
function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){if(!(a instanceof Array)){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:aa(a)};for(var c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}
function ca(a,b,c,d,f){document.getElementById("confirmmessage").innerHTML=a;document.getElementById("bno").value=b;document.getElementById("bno").onclick=function(){document.getElementById("confirmd").style.display="none";c()};document.getElementById("byes").value=d;document.getElementById("byes").onclick=function(){document.getElementById("confirmd").style.display="none";f()};document.getElementById("confirmd").style.height=window.innerHeight+"px";document.getElementById("confirmd").style.width=
window.innerWidth+"px";document.getElementById("confirmd").style.display="flex"}
function da(a){a?(document.getElementById("intro").style.display="none",document.getElementById("intro3").style.display="none"):(a=document.createElement("img"),a.src=roundTableServer+"/api/qrcode/"+room,document.getElementById("qr").innerHTML="",document.getElementById("qr").appendChild(a),a=document.createElement("input"),a.setAttribute("type","text"),a.classList.add("text"),a.value=roundTableServer+"#"+room,a.id="elink",document.getElementById("rlink").appendChild(a),document.getElementById("intro3").style.display=
"none",document.getElementById("intro4").style.display="block",ea(),document.getElementById("bstart").addEventListener("click",function(){document.getElementById("intro").style.display="none";document.getElementById("intro4").style.display="none"}))}function ea(){var a=document.getElementById("elink");a.select();a.setSelectionRange(0,99999);document.execCommand("copy")};var fa=!1,e=0,g=document.getElementById("cursor"),ha=null,ia=null,ja=null,ka=null,h=null,la=null,ma=null,na=null,oa=null,pa=null,qa=!1;
function k(){if(roundTable||n)ra();else{sa=Math.min(200,.2*Math.max(window.innerWidth*window.innerHeight));var a=document.getElementById("slidespace");a.style.height=window.innerHeight+"px";a.style.width=.8*window.innerWidth+"px";a.style.marginLeft=.1*window.innerWidth+"px";a.style.fontSize="1em";document.body.style.fontSize=Math.round(window.innerWidth/1920*40)+"px";if(t){var b=document.getElementById("sketchpad");b.setAttribute("width",.8*window.innerWidth+"px");b.setAttribute("height",window.innerHeight+
"px")}fa?document.getElementById("controlspace").children[1].classList.add("fullscreenopened"):document.getElementById("controlspace").children[1].classList.remove("fullscreenopened");b=document.getElementById("zoomedim");null!==b&&(b.style.width=.8*window.innerWidth+"px",b.style.height=window.innerHeight+"px");if(b=document.getElementById("drawinghelp"))b.parentElement.removeChild(b),ta();ua();if(a=document.getElementById("presentervideo")){b=Math.round(.1*window.innerWidth);var c=Math.round(b/640*
480);a.setAttribute("width",b+"px");a.setAttribute("height",c+"px")}a=document.getElementsByClassName("demoCameraStream");for(var d=0;d<a.length;d+=1){var f=document.getElementById("demovideo"+d);f&&(b=f.parentElement.clientWidth,c=f.parentElement.clientHeight,f.setAttribute("width",b+"px"),f.setAttribute("height",c+"px"))}}}
function va(){var a=wa("a");void 0!==a&&(roundTableAuth=a);a=wa("r");void 0!==a&&(roundTableServer=decodeURIComponent(a));a=wa("l");void 0!==a&&(room=a);document.getElementById("slidespace").addEventListener("mousemove",xa);document.getElementById("slidespace").addEventListener("mouseleave",za);document.getElementById("slidespace").addEventListener("touchmove",Aa);document.getElementById("slidespace").addEventListener("touchend",za);na=Ba;window.onkeyup=function(d){if(!roundTable&&!n&&"block"!=document.getElementById("controlspace").children[16].style.display){var f=
d.keyCode;d.preventDefault();39===f?Ca():37===f&&Da()}};window.addEventListener("resize",k);window.addEventListener("popstate",function(){Ea();u(!0)});a=document.getElementById("controlspace");var b=document.getElementById("cameraspace"),c=document.getElementById("roundtable_participants");leftHanded?(a.style.right="0px",b.style.left="0px",c.style.left="0px",!presenter&&roundTableAuth&&(document.getElementById("semaphore").style.left="0px")):(a.style.left="0px",b.style.right="0px",c.style.right="0px");
a=a.children;a[0].style.display="none";a[0].addEventListener("click",function(){null!=roundTableExit&&roundTableExit()});a[1].addEventListener("click",function(d){if(fa)document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.webkitCancelFullScreen?document.webkitCancelFullScreen():document.msExitFullscreen&&document.msExitFullscreen(),fa=!1;else{var f=document.documentElement;fa=!0;f.requestFullscreen?f.requestFullscreen():f.mozRequestFullScreen?
f.mozRequestFullScreen():f.webkitRequestFullScreen?f.webkitRequestFullScreen():f.msRequestFullscreen?f.msRequestFullscreen():fa=!1}d.preventDefault()});a[2].onclick=function(d){Ca();d.preventDefault()};a[3].onclick=function(d){Da();d.preventDefault()};a[4].addEventListener("click",function(d){v();d.preventDefault()});a[4].style.display="none";a[5].addEventListener("click",function(d){document.getElementById("controlspace").children[4].style.backgroundImage='url("./caroline/images/draw.png")';Fa();
d.preventDefault()});a[6].children[0].style.backgroundColor="rgb(0,0,0)";a[6].addEventListener("mousedown",function(d){w=[0,0,0,255];document.getElementById("cursor").children[0].style.backgroundColor="rgba(0,0,0,0.7)";d.preventDefault();if(d=document.getElementById("textannotation"))d.style.color="rgb("+w[0]+","+w[1]+","+w[2]+")"});a[6].style.display="none";a[7].children[0].style.backgroundColor="rgb(231,70,73)";a[7].addEventListener("mousedown",function(d){w=[231,70,73,255];document.getElementById("cursor").children[0].style.backgroundColor=
"rgba(231,70,73,0.7)";d.preventDefault();if(d=document.getElementById("textannotation"))d.style.color="rgb("+w[0]+","+w[1]+","+w[2]+")"});a[7].style.display="none";a[8].children[0].style.backgroundColor="rgb(246,209,84)";a[8].addEventListener("mousedown",function(d){w=[246,209,84,255];document.getElementById("cursor").children[0].style.backgroundColor="rgba(246,209,84,0.7)";d.preventDefault();if(d=document.getElementById("textannotation"))d.style.color="rgb("+w[0]+","+w[1]+","+w[2]+")"});a[8].style.display=
"none";a[9].children[0].style.backgroundColor="rgb(58,124,242)";a[9].addEventListener("mousedown",function(d){w=[58,124,242,255];document.getElementById("cursor").children[0].style.backgroundColor="rgba(58,124,242,0.7)";d.preventDefault();if(d=document.getElementById("textannotation"))d.style.color="rgb("+w[0]+","+w[1]+","+w[2]+")"});a[9].style.display="none";a[10].style.display="none";a[10].addEventListener("click",function(d){y=10<y?Math.round(.9*y):Math.round(y-1);1>y&&(y=1);Ga=Math.max(2,Math.round(.05*
y));d.target.innerHTML=y+" px";g.children[0].style.height=y+"px";g.children[0].style.width=y+"px";null!=ha&&clearTimeout(ha);ha=setTimeout(function(){document.getElementById("controlspace").children[10].innerHTML=""},1E3);d.preventDefault()});a[11].style.display="none";a[11].addEventListener("click",function(d){y=10<y?Math.round(1.1*y):Math.round(y+1);60<y&&(y=60);Ga=Math.max(2,Math.round(.05*y));d.target.innerHTML=y+" px";g.children[0].style.height=y+"px";g.children[0].style.width=y+"px";null!=ia&&
clearTimeout(ia);ia=setTimeout(function(){document.getElementById("controlspace").children[11].innerHTML=""},1E3);d.preventDefault()});a[12].addEventListener("click",function(d){document.getElementById("controlspace").children[4].style.backgroundImage='url("./caroline/images/text.png")';Ha();document.getElementById("slidespace").addEventListener("click",Ia,!0);d.preventDefault()});presenter||(a[13].style.display="none");a[13].addEventListener("click",function(d){Ja();d.preventDefault()});a[14].style.display=
"none";a[14].addEventListener("click",function(){document.getElementById("selectedimage").click()});document.getElementById("selectedimage").addEventListener("change",Ka);a[15].style.display="none";a[15].addEventListener("click",function(d){d.preventDefault();null==La&&null==z[B].file?Ma():null!=z[B].file?ca("Do you want to download shared source code file (without annotations)<br> or annotated image of the full source code?","Download shared file",function(){Na(z[B].file,Oa()+"-code"+z[B].b,"text/plain")},
"Get annotated code as png",Ma):ca("Do you want to download shared PDF (without annotations)<br> or annotated image of current view (single page)?","Download shared PDF",function(){Na(La,Oa()+"-PDF.pdf","application/pdf")},"Get current annotated view",Ma)});a[16].style.display="none";a[16].addEventListener("mousedown",function(d){C=Math.min(Math.round(1.1*C*100)/100,6);var f=document.getElementById("textannotation");null!=f&&(f.style.fontSize=C+"em");d.target.innerHTML=C;null!=ja&&clearTimeout(ja);
ja=setTimeout(function(){document.getElementById("controlspace").children[16].innerHTML=""},1E3);d.preventDefault()});a[17].style.display="none";a[17].addEventListener("mousedown",function(d){C=Math.max(Math.round(C/1.1*100)/100,.35);var f=document.getElementById("textannotation");null!=f&&(f.style.fontSize=C+"em");d.target.innerHTML=C;null!=ka&&clearTimeout(ka);ka=setTimeout(function(){document.getElementById("controlspace").children[17].innerHTML=""},1E3);d.preventDefault()});a[18].style.display=
"none";a[18].addEventListener("click",function(d){if(0<D){roundTable&&E.emit("send_room",{action:"remove",id:D,username:username,room:room});var f=document.getElementById("l"+D+"-"+username);f.parentElement.removeChild(f);--D}d.preventDefault()});a[19].style.display="none";a[19].onclick=function(d){roundTable&&E.emit("send_room",{action:"clearAll",username:username,room:room});F();d.preventDefault()};a[20].style.display="none";a[20].addEventListener("click",function(){roundTable&&E.emit("send_room",
{action:"surface_new",id:B,room:room});Pa(B)});a=document.getElementById("slidespace");a.addEventListener("mousedown",Qa,!1);a.addEventListener("mouseup",Ra,!1);a.addEventListener("touchstart",Qa,!1);a.addEventListener("touchend",Ra,!1);a=document.getElementById("cameraspace").children[0];a.addEventListener("click",function(){Sa()});a=window.location.hash.substr(1);document.getElementById("cameraspace").style.display=presenter?"block":"none";document.getElementById("controlspace").style.display="block";
document.getElementById("slidespace").style.display="block";oa=function(){};void 0===window.presentationSemaphore&&(window.presentationSemaphore=-1);window.hasOwnProperty("presentationSemaphore")||(window.presentationSemaphore=-1);!roundTable&&(0==a.indexOf("slide")||10>a.length)?presenter&&""!=presentationServer?(username="Lecturer",-1!=presentationSemaphore&&(document.getElementById("semaphore").innerHTML="<div></div><div></div><div></div>"),Ta()):!presenter&&roundTableAuth?(username="Audience",
Ua(),Va()):(Ea(),u()):Ja()}function Ua(){E=io(roundTableServer,{query:{auth2:roundTableAuth}});Wa();window.onbeforeunload=function(){return"Are you sure you want to stop following presentation?"}}
function Xa(){e=-1;document.getElementById("slidespace").innerHTML="<div class='slide'><div class='spancenter'><h2>Follow presentation with your annotations on</h2><div id='qr'>connecting to server...</div></div></div>";document.getElementById("qr").innerHTML="<img src='"+roundTableServer+"/api/qrpres/?q="+encodeURIComponent(presentationServer)+"&a="+roundTableAuth+"&r="+encodeURIComponent(roundTableServer)+"&l="+encodeURIComponent(room)+"' ><br><input value='"+presentationServer+"?a="+roundTableAuth+
"&r="+encodeURIComponent(roundTableServer)+"&l="+encodeURIComponent(room)+"' >"}
function Va(){if(-1!=presentationSemaphore){var a=document.getElementById("semaphore");a.id="audiencesemaphore";a.innerHTML="";for(var b=["Send feedback to lecturer to slow down","Send feedback to lecturer that progress speed is OK","Send feedback to lecturer that we can speed up over this material."],c=0;3>c;c+=1){var d=document.createElement("div");d.setAttribute("data-speed",c);d.addEventListener("click",Ya);d.title=b[c];a.appendChild(d)}}}
function Ta(){G=!0;E=io(roundTableServer,{query:{pkey:roundTableAuth,site:presentationServer}});Wa();e=-1;window.onbeforeunload=function(){return"Are you sure you want to stop current presentation?"}}var H=1E6;
function Wa(){E.on("connect",function(){qa=!0;-1==username.indexOf("=")&&(username=username+"="+E.id);null==room&&(room=window.location.hash.substr(1));var a=!0;if(""==room||0==room.indexOf("slide"))room=E.id+"L",G=!0,I=.8*window.innerWidth,J=window.innerHeight,k(),a=!1,document.getElementById("roundtable_participants").innerHTML=" Participants: <span id='"+username.substr(username.indexOf("=")+1)+"'>"+username.substr(0,username.indexOf("="))+"</span>";G||(null!=h&&clearTimeout(h),h=setTimeout(oa,
6E3));E.emit("join_room",{username:username,room:room});presenter?(Ea(),0==e?Xa():(u(),null!=room&&E.emit("send_room",{action:"maxslide",i:e,room:room})),E.on("presentationstate",function(b){E.emit("presentationstate",{to:b.from,slideIndex:Math.max(e,0),roundtable:roundTable})})):(E.on("presentationstate",function(b){H=e=b.slideIndex;u();b.roundtable&&Ja()}),E.emit("presentationstate",{from:E.id,to:room.substr(0,room.length-1)}),E.emit("quizanswers",{to:room.substr(0,room.length-1),u:username,qid:presentationSemaphore,
a:1}));null!=roundTableCallBack&&roundTableCallBack(a)});E.on("initial_response",function(a){presenter||(e=H=0,u());roundTableAuth=a.token});E.io.on("reconnect_attempt",function(){E.io.opts.query={auth2:roundTableAuth}});E.on("connect_error",function(){K("Connection error.")});E.on("new_user",function(a){if(a.username!=username){var b=document.getElementById("roundtable_participants");if(null==document.getElementById(a.sid)){var c=" Participants: ";""!=b.innerHTML&&(c+=b.innerHTML.substr(15));b.innerHTML=
c+"<span id='"+a.sid+"'>"+a.username.substr(0,a.username.indexOf("="))+"</span>"}G&&E.emit("send_user",{userid:a.username.substr(a.username.indexOf("=")+1),action:"introduceNewMember",sid:a.sid,list:b.innerHTML.substr(15),tableWidth:I,tableHeight:J})}});E.on("user_disconnected",function(a){E.emit("room_user_left",{userid:a.userid,room:room,action:"memberLeft"})});E.on("m",Za);E.on("update_state",$a);E.on("quizanswers",function(a){for(;a.qid>=L.length;)L.push({});L[a.qid][a.u]=a.a;console.log(L);null!=
ab&&ab==a.qid&&bb(a.qid);if(a.qid==presentationSemaphore){console.log("updating semphore");a=[0,0,0];for(var b=presentationSemaphore,c=100/Object.keys(L[b]).length,d=Object.keys(L[b]).length,f=0;f<d;f+=1){var m=Object.keys(L[b])[f];a[L[b][m]]+=c}b=document.getElementById("semaphore").childNodes;console.log(a);for(f=0;3>f;f+=1)b[f].style.height=a[f]+"%",b[f].title=Math.round(a[f]/c)+" audience member(s) - "+Math.round(a[f])+" %"}});E.io.on("reconnect_attempt",function(){E.io.opts.query={auth2:roundTableAuth}});
E.on("connect_error",function(){K("Connection error.")})}
function bb(a){if(0==cb.length){var b=document.getElementById("responseCount"+a);null!=b&&(b.innerHTML="<input id='seeresults' data-qid="+a+" type='button' value='See responses ("+Object.keys(L[a]).length+")'>",document.getElementById("seeresults").onclick=function(){var c=document.getElementsByClassName("quizq");db="";for(var d=0;d<c.length;d+=1)db+=c[d].parentElement.outerHTML;for(cb=[];0<document.getElementsByClassName("quiza").length;)c=document.getElementsByClassName("quiza")[0],c.classList.add("resultanswer"),
c.classList.remove("quiza"),cb[parseInt(c.dataset.aid,10)]=c.outerHTML;eb(a)})}else eb(a)}
function eb(a){fb();document.getElementById("slidespace").innerHTML="<div class='slide'><div class='gridslide' style='grid-template-columns: repeat(2, 1fr); grid-template-rows: repeat(3, 33.33%)'>"+db+"<div id='resultspace' style='padding:0.3em;grid-column: 1 / 3; grid-row: 2 / 4; font-size:1.00e+00m'></div></div>";for(var b={},c=Object.keys(L[a]).length,d=0;d<c;d+=1){for(var f=Object.keys(L[a])[d],m="",l=0;l<L[a][f].length;l+=1)m+=L[a][f][l];b[m]=m in b?b[m]+1/c:1/c}c=document.createElement("table");
c.classList.add("quizresultview");for(d=0;d<Object.keys(b).length;d+=1){m=document.createElement("tr");f=Object.keys(b)[d];var p="",q=f.split("");for(l=0;l<q.length;l+=1)p+=cb[parseInt(q[l],10)]+"&nbsp;";m.innerHTML="<td>"+p+"</td><td><div class='histogram' style='width:"+100*b[f]+"%'>&nbsp;&nbsp;"+parseInt(b[f]*Object.keys(L[a]).length,10)+"</div></td>";c.appendChild(m)}document.getElementById("resultspace").appendChild(c);b=document.getElementById("responseCount"+a);null!=b&&(b.innerHTML="<input id='seeresults' data-qid="+
a+" type='button' value='Go back to questions ("+Object.keys(L[a]).length+")'>",document.getElementById("seeresults").onclick=function(){u(!0)})}var L=[],ab=null,cb=[],db=null;function wa(a){for(var b=window.location.search.substring(1).split("&"),c=0;c<b.length;c++){var d=b[c].split("=");if(d[0]==a)return d[1]}}
function Pa(a){a+=1;z=ba(z.slice(0,a)).concat([{g:[],c:null,f:1,h:[],j:null,file:null,b:null,timestamp:0,scroll:[0,0]}],ba(z.slice(a)));var b=document.getElementById("controlspace").children;1<z.length?(b[2].style.display="block",b[3].style.display="block"):(b[2].style.display="none",b[3].style.display="none");gb(a)}
function hb(){if(roundTable||n){var a=[];ib();z[B].f=M;null!=N&&(z[B].scroll=[N.scrollTop,N.scrollLeft]);for(;0<document.getElementById("slidespace").children.length;)a.push(document.adoptNode(document.getElementById("slidespace").children[0]));z[B].g=a;z[B].c=La;z[B].h=O;z[B].j=N;N=null}}
function gb(a){hb();N=null;B=a;a=P;O=z[B].h;La=z[B].c;null==z[B].g&&null!=z[B].c&&(z[B].c=new Blob([z[B].c]));null==z[B].g&&null!=z[B].file&&(z[B].file=new Blob([z[B].file]));if(null!=z[B].c)M=z[B].f,jb(z[B].c),v(),P=!1;else{kb();if(null!=z[B].g&&0<z[B].g.length)for(document.getElementById("slidespace").innerHTML="";0<z[B].g.length;)document.getElementById("slidespace").appendChild(z[B].g.pop());a?(lb(),Fa()):(mb(),v());P=a;M=1;N=z[B].j;null==z[B].g&&null!=z[B].file&&(a=/(\.jpg|\.jpeg|\.png|\.gif)$/i,
a.exec(z[B].b)&&nb(z[B].file,z[B].b),a=/(\.sh|\.c|\.cpp|\.h|\.cc|\.c\+\+|\.cxx|\.hxx|\.cs|\.css|\.txt|\.diff|\.go|\.html|\.xml|\.json|\.java|\.js|\.less|\.lua|\.make|\.gmk|\.md|\.php|\.pl|\.py|\.sql|\.r|\.rb|\.rs|\.swift|\.vb|\.yaml|\.f|\.f95|\.f90|\.f03|\.f08|\.ftn|\.for|\.mat|\.jl|\.m|\.nb|\.wl)$/i,a.exec(z[B].b)&&ob(z[B].file,z[B].b),a=/(\.ipynb)$/i,a.exec(z[B].b)&&pb(z[B].file));qb()}rb();null!=N&&(N.scrollTop=z[B].scroll[0],N.scrollLeft=z[B].scroll[1]);K("Surface "+(B+1)+" of "+z.length+".")}
function K(a){var b=document.getElementById("notify");b.children[0].innerHTML=a;b.style.display="block";null!=ma&&clearTimeout(ma);ma=setTimeout(function(){document.getElementById("notify").style.display="none"},1E3)}function sb(a){var b=Oa()+".png",c=document.createElement("a");"string"===typeof c.download?(c.href=a,c.download=b,document.body.appendChild(c),c.click(),document.body.removeChild(c)):window.open(a)}
function tb(a){a.target.style.height="auto";a.target.style.height=a.target.scrollHeight+"px"}function ub(){for(var a=document.getElementsByClassName("sframe"),b=0;b<a.length;b+=1)a[b].classList.add("canvas-inactive");a=document.getElementsByClassName("simage");for(b=0;b<a.length;b+=1)a[b].classList.add("canvas-inactive");if(null!=N)for(N.removeEventListener("pointerdown",vb),a=N.getElementsByTagName("a"),b=0;b<a.length;b+=1)a[b].classList.add("canvas-inactive")}
function Ia(a){var b=document.createElement("textarea");b.id="textannotation";b.classList.add("textannotation");b.setAttribute("placeholder","Type text or $LaTeX$...");null==N?(b.style.fontSize=C+"em",b.style.left=(a.clientX-.1*window.innerWidth)/Q+"px",b.style.top=a.clientY/Q+"px",document.getElementById("slidespace").appendChild(b)):(b.style.fontSize=C/.76+"em",b.style.left=(a.clientX-.1*window.innerWidth)/Q+N.scrollLeft+"px",b.style.top=a.clientY/Q+N.scrollTop+"px",N.appendChild(b));b.style.height=
b.scrollHeight+"px";b.style.width=roundTable?I+(.1*window.innerWidth-a.clientX)/Q+"px":.9*window.innerWidth-a.clientX+"px";b.style.color="rgb("+w[0]+","+w[1]+","+w[2]+")";b.addEventListener("input",tb,!1);b.focus();document.getElementById("slidespace").removeEventListener("click",Ia,!0);b.addEventListener("blur",wb)}
function Ha(){for(var a=document.getElementById("controlspace").children,b=4;16>b;b+=1)a[b].style.display="none";a[4].style.display="block";a[5].style.display="none";a[6].style.display="block";a[7].style.display="block";a[8].style.display="block";a[9].style.display="block";a[16].style.display="block";a[17].style.display="block";a[18].style.display="block";a[19].style.display="none";a[20].style.display="none";ub()}
function wb(a){a=a.target;var b=a.value;b=xb(b).replace(/\r?\n/g,"<br>");var c=a.parentElement;if(""==b)c.removeChild(a),v();else{var d=document.createElement("div");d.classList.add("textannotation");d.style.left=a.style.left;d.style.top=a.style.top;d.style.height="auto";d.style.width="auto";d.style.maxWidth=a.style.width;d.style.fontSize=a.style.fontSize;d.innerHTML=b;var f=a.style.color;d.style.color=f;a.parentElement.removeChild(a);D+=1;d.id="l"+D+"-"+username;d.addEventListener("dblclick",yb,
!1);d.dataset.s=b;c.append(d);MathJax.typesetClear();MathJax.typesetPromise();v();roundTable&&E.emit("send_room",{action:"text",id:D,text:b,fontSize:C,color:f,x:parseFloat(a.style.left.replace("px","")),y:parseFloat(a.style.top.replace("px","")),username:username,room:room},function(m){z[B].timestamp=m})}}
function yb(a){Ha();var b=a.target,c=document.createElement("textarea");c.id="textannotation";c.classList.add("textannotation");c.setAttribute("placeholder","Type text or $LaTeX$...");c.style.left=b.style.left;c.style.top=b.style.top;c.style.fontSize=b.style.fontSize;c.value=b.dataset.s.replace(/<br>/g,"\n").replace(/&amp;/g,"&").replace(/&lt;/,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#039;/g,"'");c.style.color=b.style.color;roundTable&&E.emit("send_room",{action:"deleteAnnotation",
id:b.id,room:room},function(d){z[B].timestamp=d});zb(b.id);null===N?document.getElementById("slidespace").appendChild(c):N.appendChild(c);c.style.height=c.scrollHeight+"px";c.style.width=roundTable?I+(.1*window.innerWidth-a.clientX)/Q+"px":.9*window.innerWidth-a.clientX+"px";c.addEventListener("input",tb,!1);c.focus();document.getElementById("slidespace").removeEventListener("click",Ia,!0);c.addEventListener("blur",wb)}
function zb(a){var b=document.getElementById(a);b.parentElement.removeChild(b);b=parseInt(a.substr(1,a.indexOf("-")),10);a=a.substr(a.indexOf("-"));for(b+=1;null!=document.getElementById("l"+b+a);)document.getElementById("l"+b+a).id="l"+(b-1)+a,b+=1;a.substr(1)==username&&--D}var E,G=!1,Q=1,J=5,I=5;
function Ka(a,b){F();void 0===b&&(b=document.getElementById("selectedimage").files[0]);5<b.size/1024/1024?alert("Only images up to 5 MB can be shared in this way. Selected image has "+Math.round(100*b.size/1024/1024)/100+" MB."):(a=/(\.jpg|\.jpeg|\.png|\.gif)$/i,a.exec(b.name)?(R=a.exec(b.name)[0],roundTable&&E.emit("send_room",{action:"image",file:b,extension:R,username:username,room:room},function(c){z[B].timestamp=c}),nb(b,R)):(a=/(\.pdf)$/i,a.exec(b.name)?(M=1,jb(b),roundTable&&E.emit("send_room",
{action:"pdf",file:b,username:username,room:room},function(c){z[B].timestamp=c})):(a=/(\.sh|\.c|\.cpp|\.h|\.cc|\.c\+\+|\.cxx|\.hxx|\.cs|\.css|\.txt|\.diff|\.go|\.html|\.xml|\.json|\.java|\.js|\.less|\.lua|\.make|\.gmk|\.md|\.php|\.pl|\.py|\.sql|\.r|\.rb|\.rs|\.swift|\.vb|\.yaml|\.f|\.f95|\.f90|\.f03|\.f08|\.ftn|\.for|\.mat|\.jl|\.m|\.nb|\.wl)$/i,a.exec(b.name)?(R=a.exec(b.name)[0],roundTable&&E.emit("send_room",{action:"code",file:b,extension:R,username:username,room:room},function(c){z[B].timestamp=
c}),ob(b,R)):(a=/(\.ipynb)$/i,a.exec(b.name)?(R=a.exec(b.name)[0],roundTable&&E.emit("send_room",{action:"ipynb",file:b,extension:R,username:username,room:room},function(c){z[B].timestamp=c}),pb(b)):alert("Invalid file type for sharing.\n Allowed types are .jpg, .jpeg, .png, .gif, .pdf, .ipynb .sh, .c, .cpp, .h, .cc, .c++, .cxx, .hxx, .cs, .css, .txt, .diff, .go, .html, .xml, .json, .java, .js, .less, .lua, .make, .gmk, .md, .php, .pl, .py, .sql, .r, .rb, .rs, .swift, .vb, .yaml, .f, .f95, .f90, .f03, .f08, .ftn, .for, .mat, .jl, .m, .nb and .wl.")))))}
function nb(a,b){kb();z[B].file=a;z[B].b=b;b=document.getElementById("slidespace").getElementsByClassName("slide")[0];var c=document.createElement("img");c.classList.add("simage");c.addEventListener("mousedown",Ab);c.setAttribute("draggable","false");c.src=URL.createObjectURL(a);b.appendChild(c);qb()}
function pb(a){var b=new FileReader;b.addEventListener("loadend",function(c){Bb();document.getElementById("slidespace").innerHTML="<div class='slide'> <div id='ipynb'></div></div>";var d=nbv_constructor(document,{md:window.markdownit().use(window.markdownitMathjax()),hljs:hljs});z[B].file=a;z[B].b=".ipynb";d.render(JSON.parse(c.target.result),document.getElementById("ipynb"));N=document.getElementById("ipynb");N.style.fontSize=Math.round(I/.8*.76/1920*40)+"px";N.style.lineHeight=Math.round(25.8667/
27.2292*(I/.8)/1920*40)+"px";N.scrollTop=z[B].scroll[0];N.scrollLeft=z[B].scroll[1];d=document.getElementById("slidespace").getElementsByTagName("code");for(c=0;c<d.length;c+=1)d[c].style.fontSize=Math.round(I/.8*.65/1920*40)+"px",d[c].style.lineHeight=Math.round(25.8667/27.2292*(I/.8)/1920*40)+"px";d=document.getElementsByTagName("div");for(c=0;c<d.length;c+=1)d[c].style.lineHeight=Math.round(30/27.2292*(I/.8)/1920*40)+"px";d=document.getElementsByTagName("p");for(c=0;c<d.length;c+=1)d[c].style.lineHeight=
Math.round(30/27.2292*(I/.8)/1920*40)+"px";d=document.getElementsByTagName("pre");for(c=0;c<d.length;c+=1)d[c].style.lineHeight=Math.round(25.8667/27.2292*(I/.8)/1920*40)+"px";Cb();v();N.addEventListener("pointerdown",vb);N.addEventListener("scroll",Db);qb();d=N.getElementsByTagName("img");for(c=0;c<d.length;c+=1)d[c].addEventListener("mousedown",Ab),d[c].setAttribute("draggable","false"),d[c].addEventListener("load",function(){k()});k()});b.readAsText(a)}
function ob(a,b){var c=new FileReader;c.addEventListener("loadend",function(d){document.getElementById("slidespace").innerHTML="<div class='slide'> <pre><code class='language-"+Eb[b]+"'> "+xb(d.target.result)+"</pre></code></div>";hljs.highlightAll();z[B].file=a;z[B].b=b;N=document.getElementById("slidespace").getElementsByTagName("code")[0];N.style.fontSize=Math.round(I/.8*.76/1920*40)+"px";N.style.lineHeight=Math.round(25.8667/27.2292*(I/.8)/1920*40)+"px";N.scrollTop=z[B].scroll[0];N.scrollLeft=
z[B].scroll[1];Cb();v();k();N=document.getElementById("slidespace").getElementsByTagName("code")[0];N.addEventListener("pointerdown",vb);N.addEventListener("scroll",Db);qb();d=document.getElementById("slidespace").getElementsByClassName("slide")[0];var f=document.createElement("div");f.classList.add("pdfcontrol");f.innerHTML='<button id="dark">Dark</button>  <button id="light">Light</button>';d.append(f);document.getElementById("light").addEventListener("click",function(){Bb();E.emit("send_room",
{action:"code_light",username:username,room:room})});document.getElementById("dark").addEventListener("click",function(){Fb();E.emit("send_room",{action:"code_dark",username:username,room:room})})});c.readAsText(a)}function Db(a){pa==username&&roundTable&&E.emit("send_room",{action:"scroll",top:a.target.scrollTop,left:a.target.scrollLeft,username:username,room:room})}
function Bb(){document.getElementById("codedarkcss").setAttribute("disabled","disabled");document.getElementById("codelightcss").removeAttribute("disabled")}function Fb(){document.getElementById("codelightcss").setAttribute("disabled","disabled");document.getElementById("codedarkcss").removeAttribute("disabled")}
var N=null,Gb={top:0,left:0,x:0,y:0},R=null,Eb={".sh":"bash",".c":"c",".cpp":"c",".h":"c",".cc":"c",".c++":"c",".cxx":"c",".hxx":"c",".cs":"csharp",".css":"css",".txt":"txt",".diff":"diff",".go":"go",".html":"html",".xml":"xml",".json":"json",".java":"java",".js":"js",".less":"less",".lua":"lua",".make":"make",".gmk":"make",".md":"mf",".php":"php",".pl":"perl",".py":"python",".sql":"sql",".r":"r",".rb":"ruby",".rs":"rust",".swift":"swift",".vb":"vbnet",".yaml":"yaml",".f":"fortran",".f95":"fortran",
".f90":"fortran",".f03":"fortran",".f08":"fortran",".ftn":"fortran",".for":"fortran",".mat":"matlab",".jl":"julia",".m":"mathematica",".nb":"mathematica",".wl":"mathematica"};function vb(a){pa=username;Gb={left:N.scrollLeft,top:N.scrollTop,x:a.clientX,y:a.clientY};N.style.userSelect="none";document.addEventListener("pointermove",Hb);document.addEventListener("pointerup",Ib)}function Hb(a){var b=a.clientX-Gb.x;N.scrollTop=Gb.top-(a.clientY-Gb.y)/Q;N.scrollLeft=Gb.left-b/Q}
function Ib(){N.style.removeProperty("user-select");document.removeEventListener("pointermove",Hb);document.removeEventListener("pointerup",Ib)}
function ib(){var a=M;if(!Jb){for(var b=[];0<document.getElementsByClassName("textannotation").length;)b.push(document.adoptNode(document.getElementsByClassName("textannotation")[0]));var c="";null!=document.getElementById("sketchpad")&&(c=document.getElementById("sketchpad").innerHTML,document.getElementById("sketchpad").innerHTML="");O[a]={svg:c,text:b}}}
function qb(){var a=M;if(void 0!=O[a]){for(document.getElementById("sketchpad").innerHTML+=O[a].svg;0<O[a].text.length;)document.getElementById("sketchpad").parentElement.appendChild(O[a].text.pop());rb();MathJax.typesetClear();MathJax.typesetPromise()}}var O={};
function jb(a){kb();La=a;z[B].c=a;document.getElementById("slidespace").getElementsByClassName("slide")[0].innerHTML+='<canvas id="pdf-canvas"></canvas>';T=document.getElementById("pdf-canvas");Kb=T.getContext("2d");pdfjsLib.getDocument(URL.createObjectURL(a)).promise.then(function(b){Lb=b;if(1<Lb.numPages){b=document.getElementById("slidespace").getElementsByClassName("slide")[0];var c=document.createElement("div");c.classList.add("pdfcontrol");c.innerHTML='<button id="prev">&nbsp;&lt;&nbsp;&lt;&nbsp;</button> <span><span id="textpdfpage">1</span><input type="range" id="pdfpage" name="pdfPage"  min="1" max="1"><span> <button id="next">&nbsp;&gt;&nbsp;&gt;&nbsp;</button>';
b.append(c);document.getElementById("pdfpage").max=Lb.numPages;document.getElementById("pdfpage").addEventListener("change",function(){var d=parseInt(document.getElementById("pdfpage").value,10);ib();M=d;Mb(d)});document.getElementById("prev").addEventListener("click",Nb);document.getElementById("next").addEventListener("click",Ob)}Pb(M)})}var La=null,Lb=null,M=1,Jb=!1,Qb=null,T=null,Kb=null;
function Pb(a){z[B].f=M;Jb=!0;Lb.getPage(a).then(function(c){var d=c.getViewport({scale:1});d=c.getViewport({scale:Math.min(I/d.width,J/d.height)});T.height=d.height;T.width=d.width;T.style.height=d.height+"px";T.style.width=d.width+"px";T.style.marginLeft=(I-d.width)/2+"px";T.style.marginTop=(J-d.height)/2+"px";c.render({canvasContext:Kb,viewport:d}).promise.then(function(){Jb=!1;null!==Qb?(Pb(Qb),Qb=null):qb()})});var b=document.getElementById("pdfpage");null!=b&&(b.value=a)}
function Mb(a){Rb(a);E.emit("send_room",{action:"pdf_page",page:a,username:username,room:room},function(b){z[B].timestamp=b})}function Rb(a){document.getElementById("textpdfpage").innerHTML="pdf page "+a+" of "+Lb.numPages;document.getElementById("textpdfpage").style.display="inline-block";null!=la&&clearTimeout(la);la=setTimeout(function(){document.getElementById("textpdfpage").style.display="none"},1E3);Jb?Qb=a:Pb(a)}function Nb(){1>=M||(ib(),M--,Mb(M))}
function Ob(){M>=Lb.numPages||(ib(),M++,Mb(M))}function Oa(){var a=new Date;return"roundtable_"+a.getFullYear()+"-"+(10>a.getMonth()+1?"0":"")+(a.getMonth()+1)+"-"+(10>a.getDate()?"0":"")+a.getDate()+"_at_"+(0>a.getHours()?"0":"")+a.getHours()+"-"+(0>a.getMinutes()?"0":"")+a.getMinutes()+"-"+a.getSeconds()}
function Na(a,b,c){if(null!=a)if(a=new Blob([a],{type:c||"application/octet-stream"}),"undefined"!==typeof window.navigator.msSaveBlob)window.navigator.msSaveBlob(a,b);else{var d=window.URL.createObjectURL(a);a=document.createElement("a");a.style.display="none";a.href=d;a.setAttribute("download",b);"undefined"===typeof a.download&&a.setAttribute("target","_blank");document.body.appendChild(a);a.click();document.body.removeChild(a);setTimeout(function(){window.URL.revokeObjectURL(d)},100)}}
function Ma(){var a=document.getElementById("slidespace"),b=a.style.backgroundColor;a.style.backgroundColor="white";a.getElementsByClassName("slide")[0].style.boxShadow="0px 0px 0px";var c=1980/window.innerWidth;null===N?html2canvas(a,{scale:c,logging:!1,useCORS:!0,allowTaint:!0,letterRendering:!0}).then(function(d){d=d.toDataURL("image/png");sb(d)}):(a.style.width=N.scrollWidth+"px",a.style.height=N.scrollHeight+"px",html2canvas(a,{scale:c,logging:!1,useCORS:!0,allowTaint:!0,width:N.scrollWidth,
height:N.scrollHeight/.99}).then(function(d){d=d.toDataURL("image/png");sb(d);k()}));a.style.backgroundColor=b;a.getElementsByClassName("slide")[0].style.boxShadow="0 0 15px #1e1e1e"}function F(){N=null;z[B].file=null;z[B].b=null;z[B].timestamp=0;z[B].f=1;Lb=La=null;M=1;Jb=!1;Kb=T=Qb=null;O=[];kb()}
function kb(){var a=document.getElementById("controlspace").children;a[0].style.display="block";a[1].style.display="none";a[11].style.display="block";a[13].style.display="none";a[14].style.display="block";a[15].style.display="block";a[19].style.display="block";a[20].style.display="block";document.getElementById("cameraspace").style.display="none";a=document.getElementById("slidespace");a.innerHTML="<div class='slide' ></div>";Cb();v();k();a=document.getElementById("slidespace").getElementsByClassName("slide")[0];
a.addEventListener("drop",function(b){b.preventDefault();b.dataTransfer.items?0<b.dataTransfer.items.length&&"file"===b.dataTransfer.items[0].kind&&Ka(b,b.dataTransfer.items[0].getAsFile()):0<b.dataTransfer.files.length&&Ka(b,b.dataTransfer.files[0])});document.addEventListener("dragover",function(b){b.preventDefault()});D=0}var z=[{g:[],c:null,f:1,h:[],j:null,file:null,b:null,timestamp:0,scroll:[0,0]}],B=0,Sb=!1,n=!1;
function Ja(){fb();var a=document.getElementById("controlspace").children;a[2].onclick=function(b){b.preventDefault();B<z.length-1?(gb(B+1),roundTable&&E.emit("send_room",{action:"surface_change",id:B,room:room})):K("This is last surface. Click on + to add more.")};a[2].setAttribute("title","Next surface");a[3].onclick=function(b){b.preventDefault();0<B?(gb(B-1),roundTable&&E.emit("send_room",{action:"surface_change",id:B,room:room})):K("This is the first surface.")};a[3].setAttribute("title","Previous surface");
null==z||1==z.length?(a[2].style.display="none",a[3].style.display="none"):(a[2].style.display="block",a[3].style.display="block");document.getElementById("roundtable_participants").style.display="block";Sb?(kb(),gb(B),""!=roundTableServer?roundTable=!0:n=!0):(""!=roundTableServer?roundTable=!0:n=!0,F());a[13].style.display="none";a[14].style.display="block";a[19].style.display="block";a[20].style.display="block";Sb=!0;qa?presenter?(roundTable&&E.emit("send_room",{action:"openroundtable",room:room}),
a[0].onclick=Tb):a[0].onclick=function(){alert("Only lecturer can initiate leaving of Roundtable.")}:Ub()}
function Tb(){hb();t=!1;presenter&&roundTable&&E.emit("send_room",{action:"closeroundtable",room:room});for(var a=document.getElementsByClassName("cursor"),b=0;b<a.length;b+=1)Vb(a[b]);u();n=roundTable=!1;v();a=document.getElementById("controlspace").children;a[0].style.display="none";a[1].style.display="block";a[2].onclick=function(c){Ca();c.preventDefault()};a[2].setAttribute("title","Next surface");a[3].onclick=function(c){Da();c.preventDefault()};a[3].setAttribute("title","Previous surface");
a[2].style.display="block";a[3].style.display="block";presenter&&(a[13].style.display="block");a[14].style.display="none";a[15].style.display="none";a[19].style.display="none";a[20].style.display="none";document.getElementById("roundtable_participants").style.display="none";presenter&&(document.getElementById("cameraspace").style.display="block");a=document.getElementById("slidespace");a.style.transform="scale(1,1)";k()}function Za(a){Wb(a.x*Q+.1*window.innerWidth,a.y*Q,Xb(a.u))}
function $a(a){if(roundTable)if("cursorhide"==a.action)Vb(Xb(a.username));else if("closeroundtable"==a.action)Tb();else if("line"==a.action){var b=document.createElementNS("http://www.w3.org/2000/svg","polyline");b.setAttribute("style",a.style);b.setAttribute("points",a.points);var c="l"+a.id+"-"+a.username;b.id=c;document.getElementById("sketchpad").appendChild(b);Yb(c);z[B].timestamp=a.t}else if("image"==a.action)c=new Blob([a.file]),F(),nb(c,a.extension),z[B].file=c,z[B].b=a.extension,z[B].timestamp=
a.t;else if("pdf"==a.action)F(),c=new Blob([a.file]),M=1,jb(c),z[B].timestamp=a.t;else if("pdf_page"==a.action)ib(),M=a.page,Rb(a.page),z[B].timestamp=a.t;else if("code"==a.action)c=new Blob([a.file]),F(),ob(c,a.extension),z[B].timestamp=a.t;else if("ipynb"==a.action)c=new Blob([a.file]),F(),pb(c),z[B].timestamp=a.t;else if("scroll"==a.action)pa=a.username,N.scrollTop=a.top,N.scrollLeft=a.left;else if("code_light"==a.action)Bb();else if("code_dark"==a.action)Fb();else if("blink_on"==a.action)Xb(a.username).classList.add("cursor_blinks");
else if("memberLeft"==a.action)b=document.getElementById(a.userid),b.parentElement.removeChild(b);else if("blink_off"==a.action)Xb(a.username).classList.remove("cursor_blinks");else if("remove"==a.action)c=a.id+"-"+a.username,b=document.getElementById("l"+c),b.parentElement.removeChild(b),z[B].timestamp=a.t;else if("clearAll"==a.action)F(),z[B].timestamp=a.t;else if("text"==a.action)c=a.id+"-"+a.username,b=document.createElement("div"),b.classList.add("textannotation"),b.classList.add("canvas-inactive"),
b.style.left=a.x+"px",b.style.top=a.y+"px",b.style.height="auto",b.style.width="auto",b.style.fontSize=a.fontSize+"em",b.innerHTML=a.text,b.style.color=a.color,b.id="l"+c,null==N?document.getElementById("slidespace").append(b):N.append(b),z[B].timestamp=a.t,MathJax.typesetClear(),MathJax.typesetPromise();else if("introduceNewMember"==a.action){null!=h&&clearTimeout(h);K("You have joined the Roundtable.");b=document.getElementById("roundtable_participants");b.innerHTML=" Participants: "+a.list;I=a.tableWidth;
J=a.tableHeight;ra();a=[];for(c=0;c<z.length;c+=1)a.push(z[c].timestamp);E.emit("send_user",{sid:E.id,action:"updateme",timestamps:a})}else if("surface_change"==a.action)gb(a.id);else if("surface_new"==a.action)Pa(a.id);else if("deleteAnnotation"==a.action)zb(a.id),z[B].timestamp=a.t;else if("updateme"==a.action){b=[];null!=N&&(z[B].scroll=[N.scrollTop,N.scrollLeft]);for(c=0;c<z.length;c+=1)c>=a.timestamps.length||z[c].timestamp>a.timestamps[c]?b.push({g:null,c:z[c].c,f:z[c].f,h:z[c].h,j:null,file:z[c].file,
b:z[c].b,timestamp:z[c].timestamp,scroll:z[c].scroll}):b.push(null);E.emit("send_user",{sid:a.sid,action:"update",update:b,currentSurface:B,surface:document.getElementById("slidespace").innerHTML})}else{if("update"==a.action){b=a.update;for(c=0;c<b.length;c+=1)c>=z.length&&z.push(b[c]),null!=b[c]&&(z[c]=b[c]);B=a.currentSurface;document.getElementById("slidespace").innerHTML=a.surface;Zb();null!=z[B].c?(z[B].c=new Blob([z[B].c]),M=z[B].f,ib(),jb(z[B].c)):null!=z[B].file&&(M=z[B].f,ib(),kb(),z[B].file=
new Blob([z[B].file]),a=/(\.jpg|\.jpeg|\.png|\.gif)$/i,a.exec(z[B].b)&&nb(z[B].file,z[B].b),a=/(\.sh|\.c|\.cpp|\.h|\.cc|\.c\+\+|\.cxx|\.hxx|\.cs|\.css|\.txt|\.diff|\.go|\.html|\.xml|\.json|\.java|\.js|\.less|\.lua|\.make|\.gmk|\.md|\.php|\.pl|\.py|\.sql|\.r|\.rb|\.rs|\.swift|\.vb|\.yaml|\.f|\.f95|\.f90|\.f03|\.f08|\.ftn|\.for|\.mat|\.jl|\.m|\.nb|\.wl)$/i,a.exec(z[B].b)&&ob(z[B].file,z[B].b),a=/(\.ipynb)$/i,a.exec(z[B].b)&&pb(z[B].file));v();a=document.getElementById("controlspace").children;1<z.length?
(a[2].style.display="block",a[3].style.display="block"):(a[2].style.display="none",a[3].style.display="none")}}else if("maxslide"==a.action)presenter||(H=Math.max(H,a.i),H==e+1?Ca():a.i>e&&K("You are behind the lecturer (slide "+e+"/"+H+")"));else if("openroundtable"==a.action)Ja();else if("memberLeft"==a.action)c=document.getElementById(a.userid),c.parentElement.removeChild(c);else if("introduceNewMember"==a.action){null!=h&&clearTimeout(h);c=document.getElementById("roundtable_participants");c.innerHTML=
" Participants: "+a.list;I=a.tableWidth;J=a.tableHeight;a=[];for(c=0;c<z.length;c+=1)a.push(z[c].timestamp);E.emit("send_user",{sid:E.id,action:"updateme",timestamps:a})}else if("updateme"==a.action){b=[];null!=N&&(z[B].scroll=[N.scrollTop,N.scrollLeft]);for(c=0;c<z.length;c+=1)c>=a.timestamps.length||z[c].timestamp>a.timestamps[c]?b.push({g:null,c:z[c].c,f:z[c].f,h:z[c].h,j:null,file:z[c].file,b:z[c].b,timestamp:z[c].timestamp,scroll:z[c].scroll}):b.push(null);E.emit("send_user",{sid:a.sid,action:"update",
update:b,currentSurface:B,surface:document.getElementById("slidespace").innerHTML})}else if("update"==a.action)for(b=a.update,c=0;c<b.length;c+=1)c>=z.length&&z.push(b[c]),null!=b[c]&&(z[c]=b[c])}
function Ub(){""==roundTableServer?(n=!0,I=.8*window.innerWidth,J=window.innerHeight,G=!0,roundTable=!1,document.getElementById("controlspace").children[0].onclick=Tb,ra()):(n=!1,E=io(roundTableServer,{query:{auth:roundTableAuth}}),E.on("connect",function(){-1==username.indexOf("=")&&(username=username+"="+E.id);room=window.location.hash.substr(1);var a=!0;if(""==room||0==room.indexOf("slide"))a=new Uint32Array(1),window.crypto.getRandomValues(a),room=E.id+a,history.pushState("","",location.protocol+
"//"+location.host+location.pathname+"#"+room),G=!0,I=.8*window.innerWidth,J=window.innerHeight,k(),a=!1,document.getElementById("roundtable_participants").innerHTML=" Participants: <span id='"+username.substr(username.indexOf("=")+1)+"'>"+username.substr(0,username.indexOf("="))+"</span>";G||(null!=h&&clearTimeout(h),h=setTimeout(oa,6E3));E.emit("join_room",{username:username,room:room});null!=roundTableCallBack&&roundTableCallBack(a)}),E.on("initial_response",function(a){roundTableAuth=a.token}),
E.io.on("reconnect_attempt",function(){E.io.opts.query={auth2:roundTableAuth}}),E.on("connect_error",function(){K("Connection error.")}),E.on("new_user",function(a){if(a.username!=username){var b=document.getElementById("roundtable_participants");if(null==document.getElementById(a.sid)){var c=" Participants: ";""!=b.innerHTML&&(c+=b.innerHTML.substr(15));b.innerHTML=c+"<span id='"+a.sid+"'>"+a.username.substr(0,a.username.indexOf("="))+"</span>"}G&&E.emit("send_user",{userid:a.username.substr(a.username.indexOf("=")+
1),action:"introduceNewMember",sid:a.sid,list:b.innerHTML.substr(15),tableWidth:I,tableHeight:J})}}),E.on("user_disconnected",function(a){E.emit("room_user_left",{userid:a.userid,room:room,action:"memberLeft"})}),E.on("m",Za),E.on("update_state",$a))}
function Xb(a){var b=document.getElementById("c"+a);null==b&&(b=document.createElement("div"),b.classList.add("cursor"),b.id="c"+a,b.innerHTML='<div class="cursor-icon"><div class="cursor-name">'+a.substr(0,a.indexOf("="))+"</div></div>",document.getElementById("cursor").parentElement.appendChild(b));return b}var $b;
function ac(a,b,c){var d;void 0===b?d=document.getElementById("cameraspace"):d=b;void 0===c&&(c=function(l){l.target&&bc(l.target.dataset.l,l.target.dataset.facing)});d.innerHTML="<p>Select camera:</p>";var f=document.createElement("ul"),m=0;a.forEach(function(l){"videoinput"===l.kind&&(m+=1)});1==m&&(b=document.createElement("li"),b.dataset.facing="user",b.innerHTML="Front facing",b.addEventListener("click",c),f.append(b),b=document.createElement("li"),b.dataset.facing="environment",b.innerHTML=
"Back facing",b.addEventListener("click",c),f.append(b));a.forEach(function(l){if("videoinput"===l.kind){var p=document.createElement("li");p.dataset.l=l.deviceId;l=l.label||"Camera "+m++;p.innerHTML=l;p.addEventListener("click",c);f.append(p)}});d.append(f)}function Sa(a,b){navigator.mediaDevices&&navigator.mediaDevices.getUserMedia&&navigator.mediaDevices.enumerateDevices().then(function(c){ac(c,a,b)})}
function bc(a,b){var c={video:!0};void 0!==a&&""!=a?c={video:{deviceId:{exact:a}},audio:!1}:void 0!==b&&""!=b&&(c={video:{facingMode:b},audio:!1});document.getElementById("cameraspace").innerHTML="Adding camera...";navigator.mediaDevices&&navigator.mediaDevices.getUserMedia&&navigator.mediaDevices.getUserMedia(c).then(function(d){$b=d;var f=document.createElement("video");f.id="presentervideo";var m=Math.round(.1*window.innerWidth),l=Math.round(m/640*480);f.setAttribute("width",m+"px");f.setAttribute("height",
l+"px");m=document.getElementById("cameraspace");m.innerHTML="";m.append(f);f.addEventListener("click",function(){$b.getTracks().forEach(function(r){"live"==r.readyState&&r.stop()});var p=document.getElementById("cameraspace");p.removeChild(p.children[0]);var q=document.createElement("div");q.classList.add("camera");q.title="Add camera in the corner";q.addEventListener("click",function(){Sa()});p.append(q)});f.title="Click to stop camera";f.srcObject=d;f.play()})}
function Qa(){P||g.classList.contains("cursor_blinks")||(g.classList.add("cursor_blinks"),roundTable&&E.emit("send_room",{action:"blink_on",username:username,room:room}))}function Ea(){var a=window.location.hash.substr(1);e=0;""!=a&&0==a.indexOf("slide")&&(a=a.substring(5),e=parseInt(a,10))}function Ra(){g.classList.contains("cursor_blinks")&&(g.classList.remove("cursor_blinks"),roundTable&&E.emit("send_room",{action:"blink_off",username:username,room:room}))}
var t=!1,P=!1,cc=null,dc,ec,fc=0,U,V,y=5,C=1,w=[0,0,0,255],Ga=2;
function v(){P&&(document.getElementById("sketchpad").classList.add("canvas-inactive"),P=!1,mb());var a=document.getElementById("controlspace").children;a[4].style.display="none";a[5].style.display="block";a[6].style.display="none";a[7].style.display="none";a[8].style.display="none";a[9].style.display="none";a[10].style.display="none";a[11].style.display="none";a[12].style.display="block";a[16].style.display="none";a[17].style.display="none";a[18].style.display="none";document.getElementById("cursor").children[0].style.backgroundColor=
"rgba(188, 40, 35, 0.7)";g.children[0].style.height="15px";g.children[0].style.width="15px";document.getElementById("slidespace").removeEventListener("click",Ia,!0);for(var b=document.getElementsByClassName("sframe"),c=0;c<b.length;c+=1)b[c].classList.remove("canvas-inactive");b=document.getElementsByClassName("simage");for(c=0;c<b.length;c+=1)b[c].classList.remove("canvas-inactive");if(null!=N)for(N.addEventListener("pointerdown",vb),b=N.getElementsByTagName("a"),c=0;c<b.length;c+=1)b[c].classList.remove("canvas-inactive");
roundTable||n?(a[14].style.display="block",a[15].style.display="block",a[19].style.display="block",a[20].style.display="block"):(a[14].style.display="none",a[19].style.display="none",presenter&&(a[13].style.display="block"))}
function Cb(){P=t=!0;var a=document.createElementNS("http://www.w3.org/2000/svg","svg");a.id="sketchpad";var b=N;null==b?(b=document.getElementById("slidespace"),a.setAttribute("width",Math.round(.8*window.innerWidth)),a.setAttribute("height",window.innerHeight)):(a.setAttribute("width",N.scrollWidth),a.setAttribute("height",N.scrollHeight));b.append(a);Zb();""!=drawingHelp&&(ta(),lb())}
function Zb(){var a=document.getElementById("sketchpad");a.addEventListener("mousedown",gc,!1);a.addEventListener("mousemove",hc,!1);window.addEventListener("mouseup",ic,!1);a.addEventListener("touchstart",jc,!1);a.addEventListener("touchmove",kc,!1);window.addEventListener("touchend",lc,!1)}function mb(){var a=document.getElementsByClassName("slide");0<a.length&&(a[0].style.backgroundColor="white")}
function lb(){if(""!=drawingHelp){var a=document.getElementsByClassName("slide");0<a.length&&(a[0].style.backgroundColor="transparent")}}
function ta(a,b){if(void 0==a||void 0==b)a=window.innerWidth,b=window.innerHeight;var c=document.getElementsByClassName("slide");if(!(1>c.length)){c=c[0];var d=Math.round(255-255*drawingHelpIntensity);d="rgb("+d+","+d+","+d+")";var f=document.createElementNS("http://www.w3.org/2000/svg","svg");f.id="drawinghelp";f.setAttribute("width",Math.round(.8*a));f.setAttribute("height",b);c.append(f);if("dots"==drawingHelp){c=Math.min(a,b)/15;var m=Math.max(3,c/15),l=Math.round(.8*a/c)+1,p=Math.round(b/c)+
1;for(a=1;a<l;a+=1)for(var q=1;q<p;q+=1)b=document.createElementNS("http://www.w3.org/2000/svg","circle"),b.setAttribute("cx",a*c),b.setAttribute("cy",q*c),b.setAttribute("stroke-width",0),b.setAttribute("fill",d),b.setAttribute("r",m),f.append(b)}else if("lines"==drawingHelp){c=Math.min(a,b)/15;m=Math.max(2,c/20);l=Math.round(.8*a/c)+1;p=Math.round(b/c)+1;q=Math.round(.8*a);for(a=1;a<p;a+=1){var r=document.createElementNS("http://www.w3.org/2000/svg","line");r.setAttribute("x1",0);r.setAttribute("y1",
a*c);r.setAttribute("x2",q);r.setAttribute("y2",a*c);r.setAttribute("style","stroke:"+d+";stroke-width:"+m);f.append(r)}for(q=1;q<l;q+=1)p=document.createElementNS("http://www.w3.org/2000/svg","line"),p.setAttribute("x1",q*c),p.setAttribute("y1",0),p.setAttribute("x2",q*c),p.setAttribute("y2",b),p.setAttribute("style","stroke:"+d+";stroke-width:"+m),f.append(p)}}}
function Fa(){g.children[0].style.height=y+"px";g.children[0].style.width=y+"px";document.getElementById("cursor").children[0].style.backgroundColor="rgba("+w[0]+","+w[1]+","+w[2]+",0.7)";t?P||(document.getElementById("sketchpad").classList.remove("canvas-inactive"),P=!0,lb()):Cb();var a=document.getElementById("controlspace").children;a[4].style.display="block";a[5].style.display="none";a[6].style.display="block";a[7].style.display="block";a[8].style.display="block";a[9].style.display="block";a[10].style.display=
"block";a[11].style.display="block";a[12].style.display="none";a[13].style.display="none";a[14].style.display="none";a[15].style.display="none";a[18].style.display="block";a[19].style.display="none";a[20].style.display="none";ub()}var W=-1,X=-1,Y=!1,D=0,mc=null;
function Ba(a,b,c,d){-1==W?(W=b,X=c,Y=!0):(Y&&(Math.abs(W-b)>sa||Math.abs(X-c)>sa)||(Y&&(D+=1,mc=document.createElementNS("http://www.w3.org/2000/svg","polyline"),mc.id="l"+D+"-"+username,mc.setAttribute("points",W+","+X),mc.setAttribute("style","stroke-linecap:round;fill:none;stroke:rgba("+w[0]+","+w[1]+","+w[2]+","+w[3]/255+");stroke-width:"+d),document.getElementById("sketchpad").append(mc),Y=!1),Math.abs(W-b)>sa||Math.abs(X-c)>sa?mc.setAttribute("points",b+","+c):mc.setAttribute("points",mc.getAttribute("points")+
" "+b+","+c)),W=b,X=c)}
function Yb(a){if(0!=a){var b=document.getElementById(a);if(null!==b){b=b.getAttribute("points").split(" ");var c=[],d=-100,f=-100;if(!(5>b.length)){for(var m=0;m<b.length;m+=1){var l=b[m].split(","),p=parseInt(l[0],10);l=parseInt(l[1],10);if(Math.abs(p-d)>Ga||Math.abs(l-f)>Ga)c.push([p,l]),d=p,f=l}if(!(5>c.length)){var q=function(r,A,x,S){A=A||r;var ya=x||r;x=ya[0]-A[0];A=ya[1]-A[1];S=Math.atan2(A,x)+(S?Math.PI:0);x=.15*Math.sqrt(Math.pow(x,2)+Math.pow(A,2));return[r[0]+Math.cos(S)*x,r[1]+Math.sin(S)*
x]};c=c.reduce(function(r,A,x,S){if(0===x)r="M "+A[0]+","+A[1];else{var ya=q(S[x-1],S[x-2],A);x=q(A,S[x-1],S[x+1],!0);r=r+" C "+(ya[0]+","+ya[1]+" "+x[0]+","+x[1]+" "+A[0]+","+A[1])}return r},"");d=document.createElementNS("http://www.w3.org/2000/svg","path");b=document.getElementById(a);b.parentElement.removeChild(b);d.setAttribute("style",b.getAttribute("style"));d.setAttribute("d",c);d.id=a;document.getElementById("sketchpad").append(d)}}}}}function gc(){fc=1;na(cc,dc,ec,y)}
function ic(a){if(0!=fc&&(fc=0,Y&&(nc(a),dc==W&&ec==X&&na(cc,dc,ec,y)),X=W=-1,!Y)){a="l"+D+"-"+username;if(roundTable){var b=document.getElementById(a);if(null===b||null===b.getAttribute("points"))return;E.emit("send_room",{action:"line",points:b.getAttribute("points"),style:b.getAttribute("style"),id:D,username:username,room:room},function(c){z[B].timestamp=c})}Yb(a)}}function hc(a){nc(a);1==fc&&na(cc,dc,ec,y)}
function nc(a){a||(a=event);a.offsetX?(dc=a.offsetX,ec=a.offsetY):a.layerX&&(dc=a.layerX,ec=a.layerY)}function jc(a){oc(a);na(cc,U/Q,V/Q,y);event.preventDefault()}
function lc(a){Y&&(oc(a),U==W&&V==X&&na(cc,U/Q,V/Q,y));X=W=-1;Y||(a=document.getElementById("l"+D+"-"+username),null!==a&&null!==a.getAttribute("points")&&(roundTable&&E.emit("send_room",{action:"line",points:a.getAttribute("points"),style:a.getAttribute("style"),id:D,username:username,room:room},function(b){z[B].timestamp=b}),Yb("l"+D+"-"+username)))}function kc(a){oc(a);na(cc,U/Q,V/Q,y);event.preventDefault()}
function oc(a){a||(a=event);a.touches&&1==a.touches.length&&(a=a.touches[0],U=a.pageX-.1*window.innerWidth+a.target.parentElement.scrollLeft*Q,V=a.pageY-a.target.parentElement.offsetTop+a.target.parentElement.scrollTop*Q)}var sa=1E3;
function ra(){sa=Math.min(200,.2*Math.max(window.innerWidth*window.innerHeight));var a=document.getElementById("slidespace");a.style.height=J+"px";a.style.width=I+"px";a.style.marginLeft=.1*window.innerWidth+"px";document.body.style.fontSize=Math.round(window.innerWidth/1920*40)+"px";Q=1/Math.max(I/(.8*window.innerWidth),J/window.innerHeight);a.style.fontSize=I/.8/1920*40+"px";a.style.transform="scale("+Q+","+Q+")";a.style.transformOrigin="top left";t&&(a=document.getElementById("sketchpad"),null==
N?(a.setAttribute("width",I+"px"),a.setAttribute("height",J+"px")):(a.setAttribute("width",N.scrollWidth+"px"),a.setAttribute("height",N.scrollHeight+"px")));fa?document.getElementById("controlspace").children[1].classList.add("fullscreenopened"):document.getElementById("controlspace").children[1].classList.remove("fullscreenopened");a=document.getElementById("zoomedim");null!==a&&(a.style.width=.8*window.innerWidth+"px",a.style.height=window.innerHeight+"px");if(a=document.getElementById("drawinghelp"))a.parentElement.removeChild(a),
ta(I/.8,J)}var pc=-1;
function fb(){if(-1!=pc&&!roundTable&&!n&&(pc!=data.slides.length&&t&&(data.slides[pc].canvas=document.getElementById("sketchpad").innerHTML),pc!=data.slides.length&&null!=pc)){for(var a=[],b=document.getElementsByClassName("textannotation"),c=0;c<b.length;c+=1)null!=b[c].id&&a.push({id:b[c].id,left:b[c].style.left,top:b[c].style.top,color:b[c].style.color,maxWidth:b[c].style.maxWidth,fontSize:b[c].style.fontSize,m:b[c].innerHTML,text:b[c].dataset.s});data.slides[pc].textAnnotation=a}pc=e}
function u(a){a=void 0===a?!1:a;if(-1==e)Xa();else if(null!=a&&0!=a||history.pushState("","",location.protocol+"//"+location.host+location.pathname+"#slide"+e),0==cb.length&&fb(),e>=data.slides.length)qc();else{a=""!=data.slides[e].style?"style='"+data.slides[e].style.replace("'",'"')+"'":null===logoURL?"":"style='background-image: url("+logoURL+");background-size: 13%;background-repeat: no-repeat;background-position: bottom right;background-origin: border-box;'";var b=document.getElementById("slidespace");
b.innerHTML="<div class='slide'"+a+">"+data.slides[e].html+"</div>";if(null!=data.slides[e].textAnnotation){var c=data.slides[e].textAnnotation;for(a=0;a<c.length;a+=1){var d=document.createElement("div");d.classList.add("textannotation");d.id=c[a].id;d.style.left=c[a].left;d.style.top=c[a].top;d.style.color=c[a].color;d.style.maxWidth=c[a].maxWidth;d.style.fontSize=c[a].fontSize;d.innerHTML=c[a].m;d.style.height="auto";d.style.width="auto";d.addEventListener("dblclick",yb,!1);d.dataset.s=c[a].text;
b.appendChild(d)}}P?(P=t=!1,Fa()):t=!1;""!=data.slides[e].canvas&&(t||(Cb(),v()),document.getElementById("sketchpad").innerHTML=data.slides[e].canvas);rb();b=b.getElementsByClassName("simage");for(a=0;a<b.length;a+=1)b[a].addEventListener("dblclick",function(f){var m=document.createElement("div");m.id="zoomedim";m.style.width=.8*window.innerWidth+"px";m.style.height=window.innerHeight+"px";m.innerHTML="<img src='"+f.target.src+"' class='simage' alt='zoomed figure'>";m.addEventListener("dblclick",
rc,!1);document.getElementById("slidespace").append(m)}),b[a].addEventListener("mousedown",Ab),b[a].setAttribute("draggable","false");document.addEventListener("dragstart",function(f){f.preventDefault()});cb=[];b=document.getElementsByClassName("quiza");for(a=0;a<b.length;a+=1)b[a].addEventListener("click",sc);presenter&&0<b.length?(ab=b[0].dataset.qid,L.length>ab&&0<Object.keys(L[ab]).length&&bb(ab)):ab=null;tc();uc=[];vc=[];k();ua();try{MathJax.typesetClear(),MathJax.typesetPromise()}catch(f){console.log("warning: ",
f)}}}function sc(a){a=a.target;a.classList.contains("quiza")||(a=a.parentElement);a.classList.contains("selected")?a.classList.remove("selected"):a.classList.add("selected");if(!presenter){a=[];for(var b=document.getElementsByClassName("quiza"),c=b[0].dataset.qid,d=0;d<b.length;d+=1)b[d].classList.contains("selected")&&a.push(b[d].dataset.aid);K("You have selected "+a.length+" answer"+(1==a.length?"":"s")+".");E.emit("quizanswers",{to:room.substr(0,room.length-1),u:username,qid:c,a:a})}}
function Ya(a){a=a.target;for(var b=a.parentElement.getElementsByTagName("div"),c=0;3>c;c+=1)b[c]==a?(b[c].style.webkitFilter="brightness(100%)",b[c].style.filter="brightness(100%)"):(b[c].style.webkitFilter="brightness(64%)",b[c].style.filter="brightness(64%)");presenter||(a=a.getAttribute("data-speed"),b=presentationSemaphore,0==a?K("Your feedback to lecturer: we should <b>slow down</b> here."):1==a?K("Your feedback to lecturer: this is a <b>good speed</b> of progress."):K("Your feedback to lecturer: we <b>can speed up</b> over this material."),
E.emit("quizanswers",{to:room.substr(0,room.length-1),u:username,qid:b,a:a}))}var vc=null,uc=[],Z=[];
function tc(){for(var a=0;a<Z.length;a+=1)null!=Z[a]&&Z[a].getTracks().forEach(function(f){"live"==f.readyState&&f.stop()});Z=[];var b=document.getElementsByClassName("demoCameraStream");for(a=0;a<b.length;a+=1){b[a].id="demostream"+a;if(b[a].dataset.src){var c=document.createElement("video");c.id="demovideo"+a;c.setAttribute("controls","");c.innerHTML='<source src="'+b[a].dataset.src+'" type="video/mp4">';b[a].append(c);var d=b[a].clientHeight;c.setAttribute("width","100%");c.setAttribute("height",
d+"px")}else Sa(b[a],wc);Z.push(null)}}
function wc(a){a.target&&(a=a.target);var b=a.parentElement.parentElement,c=parseInt(b.id.replace("demostream",""),10),d=a.dataset.l;a=a.dataset.facing;var f={video:!0};""!=d?f={video:{deviceId:{exact:d}},audio:!1}:""!=a&&(f={video:{facingMode:a},audio:!1});b.innerHTML="Adding camera...";navigator.mediaDevices&&navigator.mediaDevices.getUserMedia&&navigator.mediaDevices.getUserMedia(f).then(function(m){Z[c]=m;var l=document.createElement("video");l.id="demovideo"+c;var p=b.clientHeight;l.setAttribute("width",
b.clientWidth+"px");l.setAttribute("height",p+"px");l.style.maxHeight="100%";b.innerHTML="";b.append(l);l.srcObject=m;l.play();ua();m=document.createElement("div");m.classList.add("streamcontrol");p=document.createElement("div");p.innerHTML="Change source";p.addEventListener("click",function(){null!=Z[c]&&Z[c].getTracks().forEach(function(q){"live"==q.readyState&&q.stop()});Sa(b,wc)});m.append(p);p=document.createElement("div");p.innerHTML="Stop";p.addEventListener("click",function(){if(null!=Z[c]){l=
document.getElementById("demovideo"+c);var q=document.createElement("canvas");q.setAttribute("width",l.videoWidth+"px");q.setAttribute("height",l.videoHeight+"px");q.style.display="none";l.parentElement.append(q);q.getContext("2d").drawImage(l,0,0,l.videoWidth,l.videoHeight);q=q.toDataURL("image/png");var r=document.createElement("img");r.classList.add("simage");r.setAttribute("style",l.getAttribute("style"));r.addEventListener("mousedown",Ab);r.setAttribute("draggable","false");r.setAttribute("src",
q);r.addEventListener("dblclick",function(A){var x=document.createElement("div");x.id="zoomedim";x.style.width=.8*window.innerWidth+"px";x.style.height=window.innerHeight+"px";x.innerHTML="<img src='"+A.target.src+"' class='simage' alt='zoomed figure'>";x.addEventListener("dblclick",rc,!1);document.getElementById("slidespace").append(x)});r.addEventListener("mousedown",Ab);r.setAttribute("draggable","false");l.parentElement.append(r);l.style.display="none";Z[c].getTracks().forEach(function(A){"live"==
A.readyState&&A.stop()})}Z[c]=null});m.append(p);b.append(m)})}function Ab(a){a.preventDefault()}function xc(a){for(var b=0,c=0;c<a.length;c+=1)b=Math.max(b,a[c].offsetTop+a[c].clientHeight);return b-=window.innerHeight}
function ua(){var a=document.getElementsByClassName("slide");if(0<a.length){a=a[0].getElementsByTagName("div");var b=document.getElementsByClassName("sframe");if(0<b.length)if(0==vc.length)for(var c=0;c<b.length;c+=1)vc.push(b[c].clientHeight);else for(c=0;c<b.length;c+=1)b[c].style.maxHeight=vc[c]+"px";c=xc(a);for(var d=0;0<c&&d<b.length;)b[d].clientHeight>c&&(b[d].style.maxHeight=b[d].clientHeight-c+"px"),d+=1,c=xc(a);b=document.getElementsByClassName("demoCameraStream");if(0==uc)for(c=0;c<b.length;c+=
1)uc.push(-1);for(d=0;d<b.length;){var f=document.getElementById("demovideo"+d);f&&(-1==uc[d]?uc[d]=f.height:f.style.maxHeight=uc[d]+"px");d+=1}b=document.getElementsByClassName("demoCameraStream");d=0;for(c=xc(a);0<c&&d<b.length;)(f=document.getElementById("demovideo"+d))&&f.height>c&&(f.style.maxHeight=f.clientHeight-c+"px"),d+=1,c=xc(a)}}function rb(){for(D=0;document.getElementById("l"+(D+1)+"-"+username);)D+=1}
function rc(){var a=document.getElementById("zoomedim");a.parentElement.removeChild(a)}
function qc(){v();P=t=!1;document.getElementById("slidespace").innerHTML="<div class='cnotification'>End of presentation...<br><span id='presentation2pdf'>Save presentation with annotations as PDF</span><br/>This presentation is made with<img src='./caroline/images/caroline2.png' class='logo'><a class='carolinelink' target='_blank' href='https://github.com/nikolasibalic/Caroline'>https://github.com/nikolasibalic/Caroline</a><br><br>open-source Python framework for interactive web/HTML-based science presentations.</div>";document.getElementById("presentation2pdf").addEventListener("click",
yc)}var zc=null,Ac=297,Bc=210;function yc(){v();var a=.8*window.innerWidth/window.innerHeight;Ac=297;Bc=297/a;zc=new jsPDF("landscape","mm",[Ac,Bc]);e=0;u();Cc()}
function Cc(){K("Please wait. Saving slides "+Math.round((e+1)/data.slides.length*100)+" %");html2canvas(document.getElementById("slidespace"),{scale:1980/window.innerWidth,logging:!1,useCORS:!1,allowTaint:!1,letterRendering:!0,onclone:function(a){for(var b=a.getElementsByClassName("sframe");0<b.length;){var c=document.createElement("p");c.style.cssText="font-variant: normal !important; -webkit-font-variant: normal !important; font-variant-ligatures: none !important; -webkit-font-variant-ligatures: none !important; ";
var d=new String(window.location);d=d.substring(0,d.lastIndexOf("/"));var f=new String(b[0].getAttribute("src"));0==f.indexOf(".")&&(f=f.substring(1));-1==f.indexOf("http")?d+=f:d=f;d=d.replace(/&/g,"&amp;&#8203;");d=d.replace(/\//g,"&#47;&#8203;");d=d.replace(/\?/g,"?&#8203;");c.innerHTML="See interactive element at: "+d;b[0].parentElement.insertBefore(c,b[0]);b[0].parentElement.removeChild(b[0]);b=a.getElementsByClassName("sframe")}for(f=a.getElementsByTagName("mjx-assistive-mml");0<f.length;)f[0].parentElement.removeChild(f[0]),
f=a.getElementsByTagName("mjx-assistive-mml"),console.log("REMOVING")}}).then(function(a){a=a.toDataURL("image/jpeg",.8);zc.addImage(a,"JPEG",0,0,Ac,Bc);0==e&&(a=String(window.location),a=a.substring(0,a.lastIndexOf("#")),zc.textWithLink("Click here to see interactive slides.",5,5,{url:a}));e<data.slides.length-1?(zc.addPage(),e+=1,u(),Cc()):(a=new Date,zc.save("presentation_slides_"+a.getFullYear()+"-"+(10>a.getMonth()?"0":"")+a.getMonth()+"-"+(10>a.getDate()?"0":"")+a.getDate()+"_at_"+(0>a.getHours()?
"0":"")+a.getHours()+"-"+(0>a.getMinutes()?"0":"")+a.getMinutes()+"-"+a.getSeconds()+".pdf"),e+=1,qc())})}function Ca(){if(e<data.slides.length)if(presenter)e+=1,null!=room&&E.emit("send_room",{action:"maxslide",i:e,room:room});else if(e<H)e+=1,e==H&&K("You are following the lecturer.");else{K("You cannot go beyond lecturer in presentation. Let's keep drama alive.");return}u()}function Da(){0==e&&presenter&&""!=presentationServer?(v(),fb(),pc=-1,t=!1,e=-1,Xa()):0<e&&(--e,u())}
function Vb(a){void 0==a&&(a=g);a.classList.contains("cursor_visible")&&a.classList.remove("cursor_visible");a.classList.add("cursor_hidden")}function za(){Vb();roundTable&&E.emit("send_room",{action:"cursorhide",username:username,room:room})}function Aa(a){var b=a;b||(b=event);b.touches&&1==b.touches.length&&(b=b.touches[0],U=b.pageX,V=b.pageY);Wb(U,V);a.preventDefault();roundTable&&E.emit("m",{x:(U-.1*window.innerWidth)/Q,y:V/Q,u:username,r:room})}
function Wb(a,b,c){void 0==c&&(c=g);var d=c;void 0==d&&(d=g);d.classList.contains("cursor_hidden")&&d.classList.remove("cursor_hidden");d.classList.add("cursor_visible");c.style.transform="translate("+(a-.5*c.offsetWidth)+"px, "+(b-.5*c.offsetHeight)+"px)"}function xa(a){roundTable&&E.emit("m",{x:(a.clientX-.1*window.innerWidth)/Q,y:a.clientY/Q,u:username,r:room});Wb(a.clientX,a.clientY)}
function xb(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")};window.initRoundTable=function(){var a=window.location.hash.substr(1);document.getElementById("gettable").value=""==a||0==a.indexOf("slide")?"Get my roundtable":"Join roundtable";document.getElementById("uname").focus();document.getElementById("gettable").addEventListener("click",function(){null==document.getElementById("uname").value.match(/^\s+$/)&&0<document.getElementById("uname").value.length?(username=document.getElementById("uname").value,username=username.replace("=",""),document.getElementById("intro1").style.display=
"none",document.getElementById("intro2").style.display="block",document.getElementById("about").style.display="none"):document.getElementById("uname").focus()});document.getElementById("uname").addEventListener("keyup",function(c){13==(c.which||c.keyCode)&&(null==document.getElementById("uname").value.match(/^\s+$/)&&0<document.getElementById("uname").value.length?(username=document.getElementById("uname").value,username=username.replace("=",""),document.getElementById("intro1").style.display="none",
document.getElementById("intro2").style.display="block"):document.getElementById("uname").focus())});window.addEventListener("hashchange",function(){room!=window.location.hash.substr(1)&&window.location.reload()},!1);document.getElementById("bproceed").disabled=!0;document.getElementById("bproceed").addEventListener("click",function(){document.getElementById("intro2").style.display="none";document.getElementById("intro3").style.display="block";roundTableExit=function(){ca("Do you want to exit this roundtable?",
"Cancel",function(){},"Yes, leave this roundtable",function(){window.location=roundTableServer})};roundTable=!0;roundTableAuth=grecaptcha.getResponse();roundTableCallBack=da;va();document.getElementById("controlspace").children[19].onclick=function(c){ca("Do you want to delete everything from the table (including annotations of other people)?","Cancel",function(){},"Yes, clear roundtable",function(){E.emit("send_room",{action:"clearAll",username:username,room:room});F()});c.preventDefault()};oa=function(){ca("It seems you joined a roundtable where moderator already left, or lost connection.<br> Would you like to navigate to homepage and set up your own roundable?",
"No, continue waiting",function(){},"Yes, set up my own roundtable",function(){window.location=roundTableServer})}});a=document.getElementsByClassName("rselect");for(var b=0;b<a.length;b+=1)a[b].addEventListener("click",function(c){leftHanded="left hand use"==c.target.innerHTML?!0:!1;for(var d=document.getElementsByClassName("rselect"),f=0;f<d.length;f+=1)d[f].classList.remove("rselected");c.target.classList.add("rselected")})};window.initApp=va;
window.enabaleProceed=function(){document.getElementById("bproceed").disabled=!1};window.disableProceed=function(){document.getElementById("bproceed").disabled=!0};
